# Generated by Django 3.1.7 on 2021-12-28 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
